name: CI/CD Pipeline to S3 Video Player Artifacts

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Create zip file
        run: |
          zip -r video-player-back.zip . -x ".git/*" ".github/*" ".gitignore"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::617207029622:role/github-actions-s3-video-player-artifacts-uploader-role
          aws-region: eu-west-1

      - name: Upload zip to S3 Video Player Artifacts
        run: |
          aws s3 cp video-player-back.zip s3://video-player-architecture-automation/artifacts/video-player-back.zip
