name: CI/CD Pipeline to Create REST API Golden AMI

on:
  push:
    branches:
      - main

jobs:
  create_golden_ami:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::617207029622:role/github-v-p-start-rest-api-golden-ami-automation-execution
          aws-region: eu-west-1

      - name: Start SSM Automation to Create AMI
        run: |
          aws ssm start-automation-execution \
            --document-name "video-player-rest-api-golden-ami-automation-document" \
